services:
  backend:
    image: atchayachandrasekaran/trocare-backend:v2.0
    build: .
    container_name: rag_backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      DB_URL: mysql+asyncmy://root:${MYSQL_ROOT_PASSWORD}@mysql_db:${DB_PORT}/${MYSQL_DATABASE}
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - rag_network

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"   # Host:Container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  mysql_data:
